# Generated by Django 4.2.15 on 2025-08-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_allow_member_to_create_label_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectBasedSentimentAnalysisProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project')),
                ('allow_overlapping', models.BooleanField(default=False)),
                ('grapheme_mode', models.BooleanField(default=False)),
                ('use_relation', models.BooleanField(default=True)),
                ('type_annotation', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=20)),
                ('type_extraction', models.CharField(choices=[('triplet', 'Triplet'), ('quadruple', 'Quadruple')], default='triplet', max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.project',),
        ),
        migrations.CreateModel(
            name='DocumentSentimentAnalysisProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.project',),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'Document Classification'), ('SequenceLabeling', 'Sequence Labeling'), ('Seq2seq', 'Seq2Seq'), ('IntentDetectionAndSlotFilling', 'Intent Detection And Slot Filling'), ('Speech2text', 'Speech2Text'), ('ImageClassification', 'Image Classification'), ('BoundingBox', 'Bounding Box'), ('Segmentation', 'Segmentation'), ('ImageCaptioning', 'Image Captioning'), ('DocumentSentimentAnalysis', 'Document Sentiment Analysis'), ('AspectBasedSentimentAnalysis', 'Aspect Based Sentiment Analysis')], max_length=30),
        ),
    ]
